In [2]:
import pandas as pd
dane = pd.read_csv(r"C:\Users\wikto\Downloads\archive (2)\new_york_listings_2024.csv", low_memory = False, usecols = ["id", "name", "neighbourhood_group","room_type","price","rating", "bedrooms", "beds", "baths"])
dane.head()

,id,name,neighbourhood_group,room_type,price,rating,bedrooms,beds,baths
0,1312228,Rental unit in Brooklyn · ★5.0 · 1 bedroom,Brooklyn,Private room,55.0,5.0,1,1,Not specified
1,45277537,Rental unit in New York · ★4.67 · 2 bedrooms ·...,Manhattan,Entire home/apt,144.0,4.67,2,1,1
2,971353993633883038,Rental unit in New York · ★4.17 · 1 bedroom · ...,Manhattan,Entire home/apt,187.0,4.17,1,2,1
3,3857863,Rental unit in New York · ★4.64 · 1 bedroom · ...,Manhattan,Private room,120.0,4.64,1,1,1
4,40896611,Condo in New York · ★4.91 · Studio · 1 bed · 1...,Manhattan,Entire home/apt,85.0,4.91,Studio,1,1

In [3]:
dane.columns

Index(['id', 'name', 'neighbourhood_group', 'room_type', 'price', 'rating',
       'bedrooms', 'beds', 'baths'],
      dtype='str')

In [4]:
dane.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20758 non-null  int64
 1   name                 20758 non-null  str
 2   neighbourhood_group  20758 non-null  str
 3   room_type            20758 non-null  str
 4   price                20758 non-null  float64
 5   rating               20758 non-null  str
 6   bedrooms             20758 non-null  str
 7   beds                 20758 non-null  int64
 8   baths                20758 non-null  str
dtypes: float64(1), int64(2), str(6)
memory usage: 9.4 MB

In [5]:
dane["neighbourhood_group"].nunique()

5

In [6]:
dane["neighbourhood_group"] = dane["neighbourhood_group"].astype('category')

In [7]:
dane.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20758 non-null  int64
 1   name                 20758 non-null  str
 2   neighbourhood_group  20758 non-null  category
 3   room_type            20758 non-null  str
 4   price                20758 non-null  float64
 5   rating               20758 non-null  str
 6   bedrooms             20758 non-null  str
 7   beds                 20758 non-null  int64
 8   baths                20758 non-null  str
dtypes: category(1), float64(1), int64(2), str(5)
memory usage: 8.3 MB

In [8]:
dane["room_type"].nunique()

4

In [9]:
dane["room_type"] = dane["room_type"].astype('category')

In [10]:
dane.info(memory_usage= 'deep')

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20758 non-null  int64
 1   name                 20758 non-null  str
 2   neighbourhood_group  20758 non-null  category
 3   room_type            20758 non-null  category
 4   price                20758 non-null  float64
 5   rating               20758 non-null  str
 6   bedrooms             20758 non-null  str
 7   beds                 20758 non-null  int64
 8   baths                20758 non-null  str
dtypes: category(2), float64(1), int64(2), str(4)
memory usage: 7.1 MB

In [11]:
dane['rating'].value_counts()

rating
No rating    3593
5.0          2882
4.67          517
4.75          469
4.80          439
             ...
3.58            1
3.77            1
3.65            1
3.87            1
2.75            1
Name: count, Length: 162, dtype: int64

In [12]:
dane['rating'] = pd.to_numeric(dane['rating'], errors='coerce')
dane['rating'] = dane['rating'].astype('float16')

In [13]:
dane.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20758 non-null  int64
 1   name                 20758 non-null  str
 2   neighbourhood_group  20758 non-null  category
 3   room_type            20758 non-null  category
 4   price                20758 non-null  float64
 5   rating               17006 non-null  float16
 6   bedrooms             20758 non-null  str
 7   beds                 20758 non-null  int64
 8   baths                20758 non-null  str
dtypes: category(2), float16(1), float64(1), int64(2), str(3)
memory usage: 6.0 MB

In [14]:
dane['price'].value_counts()

price
100.0     659
150.0     575
120.0     416
200.0     405
125.0     351
         ...
778.0       1
2136.0      1
535.0       1
725.0       1
505.0       1
Name: count, Length: 785, dtype: int64

In [15]:
dane['price'].max()

np.float64(100000.0)

In [16]:
dane['price'] = dane['price'].astype('float32')

In [17]:
dane.head()

c:\Users\wikto\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,id,name,neighbourhood_group,room_type,price,rating,bedrooms,beds,baths
0,1312228,Rental unit in Brooklyn · ★5.0 · 1 bedroom,Brooklyn,Private room,55.0,5.000000,1,1,Not specified
1,45277537,Rental unit in New York · ★4.67 · 2 bedrooms ·...,Manhattan,Entire home/apt,144.0,4.671875,2,1,1
2,971353993633883038,Rental unit in New York · ★4.17 · 1 bedroom · ...,Manhattan,Entire home/apt,187.0,4.171875,1,2,1
3,3857863,Rental unit in New York · ★4.64 · 1 bedroom · ...,Manhattan,Private room,120.0,4.640625,1,1,1
4,40896611,Condo in New York · ★4.91 · Studio · 1 bed · 1...,Manhattan,Entire home/apt,85.0,4.910156,Studio,1,1

In [18]:
dane.info(memory_usage = 'deep')

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20758 non-null  int64
 1   name                 20758 non-null  str
 2   neighbourhood_group  20758 non-null  category
 3   room_type            20758 non-null  category
 4   price                20758 non-null  float32
 5   rating               17006 non-null  float16
 6   bedrooms             20758 non-null  str
 7   beds                 20758 non-null  int64
 8   baths                20758 non-null  str
dtypes: category(2), float16(1), float32(1), int64(2), str(3)
memory usage: 6.0 MB

In [19]:
dane['bedrooms'].nunique()
dane['bedrooms'].value_counts(dropna=False)

bedrooms
1         13439
2          3602
Studio     1815
3          1394
4           345
5           112
6            29
7             9
9             6
8             5
15            1
14            1
Name: count, dtype: int64

In [20]:
dane['bedrooms'] = dane['bedrooms'].replace('Studio', 0)
dane['bedrooms'] = dane['bedrooms'].astype('int8')

In [21]:
dane.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20758 non-null  int64
 1   name                 20758 non-null  str
 2   neighbourhood_group  20758 non-null  category
 3   room_type            20758 non-null  category
 4   price                20758 non-null  float32
 5   rating               17006 non-null  float16
 6   bedrooms             20758 non-null  int8
 7   beds                 20758 non-null  int64
 8   baths                20758 non-null  str
dtypes: category(2), float16(1), float32(1), int64(2), int8(1), str(2)
memory usage: 5.0 MB

In [22]:
dane[dane['bedrooms'].isin([14,15])]

c:\Users\wikto\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,id,name,neighbourhood_group,room_type,price,rating,bedrooms,beds,baths
3545,845673513670510598,Rental unit in New York · 15 bedrooms · 21 bed...,Manhattan,Entire home/apt,1815.0,NaN,15,21,6
19154,2261367,Home in Brooklyn · ★4.77 · 14 bedrooms · 42 be...,Brooklyn,Entire home/apt,2136.0,4.769531,14,42,15.5

In [23]:
dane['beds'].nunique()

17

In [24]:
dane['beds'].value_counts()

beds
1     12310
2      4834
3      2029
4       929
5       335
6       162
7        63
8        49
9        22
10       11
12        5
11        4
21        1
14        1
13        1
18        1
42        1
Name: count, dtype: int64

In [25]:
dane[dane['beds'].isin([42, 18])]

c:\Users\wikto\AppData\Local\Programs\Python\Python313\Lib\site-packages\pandas\io\formats\format.py:1466: RuntimeWarning: overflow encountered in cast
  has_large_values = (abs_vals > 1e6).any()

,id,name,neighbourhood_group,room_type,price,rating,bedrooms,beds,baths
18496,279857,Home in Brooklyn · ★4.87 · 8 bedrooms · 18 bed...,Brooklyn,Private room,1300.0,4.871094,8,18,4
19154,2261367,Home in Brooklyn · ★4.77 · 14 bedrooms · 42 be...,Brooklyn,Entire home/apt,2136.0,4.769531,14,42,15.5

In [26]:
dane['beds'] = dane['beds'].astype('int8')

In [27]:
dane.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20758 non-null  int64
 1   name                 20758 non-null  str
 2   neighbourhood_group  20758 non-null  category
 3   room_type            20758 non-null  category
 4   price                20758 non-null  float32
 5   rating               17006 non-null  float16
 6   bedrooms             20758 non-null  int8
 7   beds                 20758 non-null  int8
 8   baths                20758 non-null  str
dtypes: category(2), float16(1), float32(1), int64(1), int8(2), str(2)
memory usage: 4.8 MB

In [28]:
dane['baths'].nunique()

17

In [29]:
dane['baths'].value_counts()

baths
1                17015
2                 2082
1.5               1001
2.5                240
3                  171
0                   82
4                   69
3.5                 50
4.5                 18
Not specified       13
5                    6
6                    4
5.5                  2
6.5                  2
11.5                 1
7                    1
15.5                 1
Name: count, dtype: int64

In [30]:
dane["baths"] = pd.to_numeric(dane['baths'], errors='coerce')

In [31]:
dane[dane["baths"].isin([1.5, 2.5, 3.5])][["name", "room_type", "bedrooms", "beds", "baths"]].head(20)

,name,room_type,bedrooms,beds,baths
26,Rental unit in New York · 1 bedroom · 1 bed · ...,Private room,1,1,1.5
39,Rental unit in New York · ★4.90 · 1 bedroom · ...,Private room,1,1,1.5
59,Rental unit in New York · ★4.75 · 3 bedrooms ·...,Private room,3,1,1.5
75,Home in Brooklyn · ★4.67 · 5 bedrooms · 9 beds...,Entire home/apt,5,9,3.5
94,Rental unit in New York · 1 bedroom · 1 bed · ...,Entire home/apt,1,1,1.5
109,Rental unit in Brooklyn · 1 bedroom · 1 bed · ...,Entire home/apt,1,1,1.5
123,Home in Queens · ★4.56 · 1 bedroom · 2 beds · ...,Private room,1,2,1.5
131,Rental unit in Brooklyn · ★4.60 · 1 bedroom · ...,Private room,1,1,1.5
132,Rental unit in Brooklyn · ★4.33 · 1 bedroom · ...,Private room,1,1,1.5
151,Home in Brooklyn · ★4.33 · 1 bedroom · 1 bed ·...,Private room,1,1,1.5
170,Rental unit in Brooklyn · ★4.91 · 1 bedroom · ...,Private room,1,1,1.5
188,Rental unit in New York · 1 bedroom · 1 bed · ...,Private room,1,1,1.5
201,Townhouse in New York · ★4.86 · 4 bedrooms · 6...,Entire home/apt,4,6,2.5
257,Home in Bronx · ★4.96 · 1 bedroom · 2 beds · 1...,Private room,1,2,1.5
273,Rental unit in New York · ★4.93 · 1 bedroom · ...,Private room,1,1,1.5
283,Home in Queens · ★4.75 · 3 bedrooms · 3 beds ·...,Entire home/apt,3,3,1.5
306,Home in Rego Park · ★4.69 · 1 bedroom · 1 bed ...,Private room,1,1,1.5
307,Townhouse in Brooklyn · ★4.94 · 4 bedrooms · 4...,Entire home/apt,4,4,2.5
309,Rental unit in Brooklyn · 1 bedroom · 1 bed · ...,Private room,1,1,1.5
339,Rental unit in New York · ★4.78 · 2 bedrooms ·...,Entire home/apt,2,2,1.5

In [32]:
dane['baths'] = dane['baths'].astype('float16')

In [33]:
dane.info(memory_usage='deep')

<class 'pandas.DataFrame'>
RangeIndex: 20758 entries, 0 to 20757
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   20758 non-null  int64
 1   name                 20758 non-null  str
 2   neighbourhood_group  20758 non-null  category
 3   room_type            20758 non-null  category
 4   price                20758 non-null  float32
 5   rating               17006 non-null  float16
 6   bedrooms             20758 non-null  int8
 7   beds                 20758 non-null  int8
 8   baths                20745 non-null  float16
dtypes: category(2), float16(2), float32(1), int64(1), int8(2), str(1)
memory usage: 3.9 MB

In [34]:
dane.shape

(20758, 9)

In [35]:
dane.isna().sum()

id                        0
name                      0
neighbourhood_group       0
room_type                 0
price                     0
rating                 3752
bedrooms                  0
beds                      0
baths                    13
dtype: int64

In [36]:
dane.duplicated().sum()

np.int64(0)

In [37]:
dane.describe()

c:\Users\wikto\AppData\Local\Programs\Python\Python313\Lib\site-packages\numpy\_core\_methods.py:49: RuntimeWarning: overflow encountered in reduce
  return umr_sum(a, axis, dtype, out, keepdims, initial, where)

,id,price,rating,bedrooms,beds,baths
count,2.075800e+04,20758.000000,1.700600e+04,20758.000000,20758.000000,20745.000000
mean,3.034044e+17,187.776611,inf,1.306725,1.723721,1.177734
std,3.901216e+17,1022.797180,2.944336e-01,0.877419,1.212272,0.480225
min,2.595000e+03,10.000000,1.750000e+00,0.000000,1.000000,0.000000
25%,2.708808e+07,80.000000,4.640625e+00,1.000000,1.000000,1.000000
50%,4.993003e+07,125.000000,4.808594e+00,1.000000,1.000000,1.000000
75%,7.216019e+17,199.000000,4.929688e+00,2.000000,2.000000,1.000000
max,1.054376e+18,100000.000000,5.000000e+00,15.000000,42.000000,15.500000

In [38]:
dane.dtypes

id                        int64
name                        str
neighbourhood_group    category
room_type              category
price                   float32
rating                  float16
bedrooms                   int8
beds                       int8
baths                   float16
dtype: object

In [39]:
dane['rating'].value_counts()

rating
5.000000    2882
4.671875     517
4.750000     469
4.800781     439
4.828125     426
            ...
3.580078       1
3.769531       1
3.650391       1
3.869141       1
2.750000       1
Name: count, Length: 160, dtype: int64

In [40]:
dane['rating'] = dane['rating'].astype('float16')

In [41]:
clean_data = dane

In [42]:
import joblib
joblib.dump(clean_data, "clean_data.pkl")

['clean_data.pkl']